### PR TITLE
Adjust benchmark reference files

### PR DESCRIPTION
**Pull request by conradtchan**
For some time now, the benchmark suite has been disabled because it has been failing. The solution is to identify the changes that caused the different in results, but this requires a lot of time. This will become increasingly difficult as new commits are made and errors compound unknowingly.

I suggest changing the reference files to the current output values so that the benchmark suite passes - with the assumption that the code is currently producing reasonable results. While this is not ideal, it is an easy and practical solution that allows the benchmark suite to be used again, preventing further regression. This is no worse than disabling the benchmark suite and ignoring it entirely.

When someone has time to fix these issues, they can go back to using the original reference files and examine the commits made prior to this change.

The difference in the new results are:

**tde**
```
       particle IDs differ            0  times
          positions differ      4177029  times
  smoothing lengths differ      4159413  times
         velocities differ      4177029  times
   thermal energies differ      4177029  times

MAX RMS ERROR: 2.6852E-05
```

**passy**
```
       particle IDs differ            0  times
          positions differ       313819  times
  smoothing lengths differ          113  times
         velocities differ       515452  times
   thermal energies differ       522245  times

MAX RMS ERROR: 6.2229E-08
```

**growth**
```

       particle IDs differ            0  times
          positions differ        27993  times
  smoothing lengths differ            1  times
         velocities differ        28000  times

MAX RMS ERROR: 2.6395E-10
```

The polar test does not need to be changed.

### CODE REVIEW

**Comment by danieljprice** [comment]
I had a look at this. The reason the tde test is failing is because we put an extra constraint on the timestep control, and the benchmark test asks to run for only one timestep. So the reason for the difference is that the code is actually *more* accurate in this case.

changing the timestep control slightly is a good example of where the benchmarks will fail the "sameness" tests but without anything being actually wrong in the code (e.g. conservation properties may even improve)

so short answer yes we can update the reference snapshots, but the same problem will crop up in future, e.g. checking for identical particle positions will always fail if dt changes.

If I remove the additional timestep constraint in force.F90 the tde benchmark is the same to 10^-18

**Comment by danieljprice** [comment]
...and the reason this does not affect the polar test is because the extra tilmestep constraint does not do anything in that case

**Comment by danieljprice** [comment]
specifically this line in force.F90 adds an additional timestep constraint on rapid expansion:
```
          !if (abs(fxyzu(4,i)) > epsilon(0.) .and. eni > epsilon(0.)) dtcool = C_cool*abs(eni/fxyzu(4,i))
```

**Comment by danieljprice** [comment]
I think we have to store these files on the data server instead of using git-lfs:
```
Git LFS has been disabled on the organization phantomSPH because you’ve exceeded your data plan by at least 150%. Please purchase additional data packs to cover your bandwidth and storage usage:

 https://github.com/organizations/phantomSPH/billing/data/upgrade

Current usage as of 28 Jan 2022 06:28AM UTC:

 Bandwidth: 0.0 GB / 1 GB (0%)
 Storage: 1.58 GB / 1 GB (158%)
```

**Comment by conradtchan** [comment]
It sounds like it's okay to update the reference files then. It's good to fail the test even when it's just the timestep improving, because at least you're alerted that something has changed, and have to manually update the test to confirm that it's okay.

I'll work on moving the files to the data server.

**Comment by conradtchan** [comment]
The reference files are no longer needed because #9 moves them to the web server. But this PR is still useful because of the new lines in the `.in` files.

**Comment by danieljprice** [comment]
The real bug here is that the new options in phantom should not be compulsory, i.e. should not require rewrite of the .in file if not present. We could also add a workaround to the benchmarking script so that phantom will rerun if the first run produced a rewrite of the .in file. 

This behaviour is what happens in the testsuite for phantomsetup, i.e. the code will rerun up to 3 times in order to rewrite the .setup file if necessary.

**Comment by danieljprice** [comment]
That is, it should not be necessary to pr the benchmark suite for .in file updates

**Comment by conradtchan** [comment]
Makes sense. Will update the script to rerun again.

**Pull request closed without merging**
